name: Scala CI

on:
  push:
    branches: [ ctyun ]
  pull_request:
    branches: [ ctyun ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run tests
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run install
        run: mvn -N install
      - name: Run package
        run: mvn clean install -Dmaven.test.skip=true
      - name: Download a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          path: assembly/target/wedatasphere-linkis-0.9.4-dist.tar.gz
