server:
  port: 90027  #The port that the module provides services (required)(该模块提供服务的端口（必须）)
spring:
  application:
    #If appName is pipeline, it will automatically fill in the entrance. For restful, it should start with cloud-
    #appName为pipeline的话会自动补齐entrance,对于restful,应该以cloud-开头
    name: pipelineentrance  #Module name for high availability (required)(模块名，用于做高可用（必须）)

#Specify the address of the eureka server for registration (required)(指定eureka Server的地址，用于注册（必须）)
eureka:
  client:
    serviceUrl:
      defaultZone: locahost
  instance:
    metadata-map:
      test: johnnwang
#required（必须）
management:
  endpoints:
    web:
      exposure:
        include: refresh,info
#    register-with-eureka: false
#    fetch-registry: false